/*
** EPITECH PROJECT, 2018
** IndieStudio
** File description:
** Id.hpp
*/

#ifndef INDIESTUDIO_ID_HPP
#define INDIESTUDIO_ID_HPP

enum id_gui {
	BUTTON_MENU_NEW_GAME = 101,
	BUTTON_MENU_SAVE,
	BUTTON_MENU_CTRL,
	BUTTON_MENU_QUIT,
	BUTTON_MENU_SAVE_BACK,
	BUTTON_MENU_CTRL_BACK,
	BUTTON_MENU_NEW_GAME_BACK,
	BUTTON1_PLAYER_LEFT,
	BUTTON1_PLAYER_RIGHT,
	BUTTON1_PLAYER_JUMP,
	BUTTON1_PLAYER_SWITCH,
	BUTTON1_PLAYER_AIMUP,
	BUTTON1_PLAYER_AIMDOWN,
	BUTTON1_PLAYER_SKIP,
	BUTTON2_PLAYER_LEFT,
	BUTTON2_PLAYER_RIGHT,
	BUTTON2_PLAYER_JUMP,
	BUTTON2_PLAYER_SWITCH,
	BUTTON2_PLAYER_AIMUP,
	BUTTON2_PLAYER_AIMDOWN,
	BUTTON2_PLAYER_SKIP,
	BUTTON3_PLAYER_LEFT,
	BUTTON3_PLAYER_RIGHT,
	BUTTON3_PLAYER_JUMP,
	BUTTON3_PLAYER_SWITCH,
	BUTTON3_PLAYER_AIMUP,
	BUTTON3_PLAYER_AIMDOWN,
	BUTTON3_PLAYER_SKIP,
	BUTTON4_PLAYER_LEFT,
	BUTTON4_PLAYER_RIGHT,
	BUTTON4_PLAYER_JUMP,
	BUTTON4_PLAYER_SWITCH,
	BUTTON4_PLAYER_AIMUP,
	BUTTON4_PLAYER_AIMDOWN,
	BUTTON4_PLAYER_SKIP,
	BUTTON_MENU_NEW_GAME_START,
	CHECK_BOX_1_PLAYER,
	CHECK_BOX_2_PLAYER,
	CHECK_BOX_3_PLAYER,
	CHECK_BOX_4_PLAYER,
	CHECK_BOX_1_TEAM,
	CHECK_BOX_2_TEAM,
	CHECK_BOX_3_TEAM,
	CHECK_BOX_4_TEAM,
	BUTTON_MENU_CONTINUE
};

enum id_scene {
	SCENE_MENU,
	SCENE_MENU_CTRL,
	SCENE_MENU_SAVE,
	SCENE_MENU_NEW_GAME,
	SCENE_GAME,
	SCENE_LOADING
};

enum id_time {
	TIME_LOADING_SWITCH,
	TIME_LOADING_QUIT,
	TIME_GAME
};

#endif //INDIESTUDIO_ID_HPP
